server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
  application:
    name: order-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

